name: Maven TEST and Pitest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build and Run Tests
      run: mvn -B test --file pom.xml -Dmaven.test.failure.ignore=true
    - name: Publish Test Report
      uses: scacap/action-surefire-report@v1
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run Mutation Coverage - NOT WORKING one
      run: mvn -B org.pitest:pitest-maven:mutationCoverage -DpitTargetTests="com.example.pitTestcontainers.pets.PetServiceNotWorking*" --file pom.xml
    - name: Run Mutation Coverage - WORKING one
      run: mvn -B org.pitest:pitest-maven:mutationCoverage -DpitTargetTests="com.example.pitTestcontainers.pets.PetServiceWorking*" --file pom.xml
    - name: Run Mutation Coverage - WORKING SINGLETON CONTAINER ones
      run: mvn -B org.pitest:pitest-maven:mutationCoverage -DpitTargetTests="com.example.pitTestcontainers.pets.PetService*SingletonContainerWorking*" --file pom.xml
